version : '2'

services:
  twitter:
    image: madderle/scaling-docker:data-producer-2.0
    container_name: twitter_02
    ports:
      - "9999:9999"
    volumes:
      - ./data-producers/Twitter:/home/ds
    command: jupyter-notebook --no-browser --port 9999 --ip='*' --allow-root
    environment:
      - MONGODB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGODB_PASS=${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - data_store


  iex:
    image: madderle/scaling-docker:data-producer-2.0
    container_name: iex_02
    ports:
      - "7777:7777"
    volumes:
      - ./data-producers/IEX:/home/ds
    command: jupyter-notebook --no-browser --port 7777 --ip='*' --allow-root
    environment:
      - MONGODB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGODB_PASS=${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - data_store

  data_store:
    image: redis:alpine


  db-data:
    restart: always
    container_name: mongodb_02
    image: mongo:3.6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27018:27018"
    volumes:
      - ./data-producers/db-data:/data/db

  # mongodbbackup:
  #   image: 'deenoize/mongodb-backup-s3:latest'
  #   container_name: mongobackup_02
  #   links:
  #     - db-data
  #   environment:
  #     - BUCKET=brandyn-twitter-sentiment-analysis
  #     - BACKUP_FOLDER=DBBackup/Development/
  #     - INIT_BACKUP=false
  #     - DISABLE_CRON=true
  #     - MONGODB_HOST=db-data
  #     - MONGODB_PORT=27018
  #     - MONGODB_USER=${MONGO_INITDB_ROOT_USERNAME}
  #     - MONGODB_PASS=${MONGO_INITDB_ROOT_PASSWORD}
